### ISSUE TITLE
Set up AWS deployment

### ISSUE THREAD

**Issue by asdobson** [CS450-ECE461/fall2016-group1-apiserver#29]
An AWS instance (@asdobson already has one going) should be used for automatic deployments, triggered by Travis CI. Deployments should only be triggered when a commit is tagged. On deployment, the MongoDB database should be reset, and the instance of the API server should be stopped and started to load the newly deployed package.

**Comment by mneal0515** [comment]
AWS EC2 Instance set up, CodeDeploy initialized, Travis-CI deploy-on-build functionality integrated.
