### ISSUE TITLE
Integrate Coveralls

### ISSUE THREAD

**Issue by bdfoster** [CS450-ECE461/fall2016-group1-apiserver#40]
[Coveralls](http://coveralls.io) is a test coverage analysis tool. While [Code Climate](http://codeclimate.com) accepts coverage information, it only reports the percentage of code that is covered by test cases. Coveralls is more in-depth and provides line-by-line analysis of test coverage.

Coveralls can be triggered by GitHub, so the necessary permissions need to be obtained. A badge should be placed at the top of the README file (next to the build badge).

**Comment by mneal0515** [comment]
Submitted pull request for Issue #40

**Comment by mneal0515** [comment]
Coveralls integrated successfully.
